const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/chatbot-concierge"
);

const eventSeed = [
  {
    title: "California State Capitol Museum Tour",
    city: "Sacramento, CA",
    link: "http://capitolmuseum.ca.gov/",
    image: "https://images.mapsofworld.com/allwonders/california-state-capitol-museum.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "At the State Capitol, the past, present and future of California interact with equal force. The building serves as both a museum and the state’s working seat of government. Visitors to the Capitol can experience California’s rich history and witness the making of history through the modern lawmaking process."
    
  },
  {
    title: "American River Bike Trail",
    city: "Sacramento, CA",
    link: "https://www.traillink.com/trail/american-river-bike-trail-(jedediah-smith-memorial-trail)/",
    image: "https://media-cdn.tripadvisor.com/media/photo-s/02/68/1b/7d/filename-img-1666-jpg.jpg",
    ages: 1,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "32 mile bike trail that starts in Discovery Park in Old Sac and ends near Folsom Lake at Beal's Point."
  },
  {
    title: "Second Saturday Art Walks",
    city: "Sacramento, CA",
    link: "https://sacramento.downtowngrid.com/2nd-saturday/",
    image: "http://sacramento.downtowngrid.com/wp-content/uploads/2016/01/Art_Walk-400x279.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "On the 2nd Saturday of every month, Sacramento galleries and local businesses host an open house evening starting at around 5:30pm until 9pm or later. Enjoy the art exhibits, local artists, food and wine, live music, street fairs and special events."
    
  },
  {
    title: "Folsom Historic District",
    city: "Sacramento, CA",
    link: "https//www.historicfolsom.org/",
    image: "https://media-cdn.tripadvisor.com/media/photo-s/01/74/d1/66/folsom-historic-district.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Historic Folsom is a destination offering a wide variety of things to do. Visit our art galleries and live theatre. Listen to live music and dance the night away at one of our nightclubs. It's also the place to go for a unique shopping experience."
  },
  {
    title: "Apple Hill",
    city: "Sacramento, CA",
    link: "http://applehill.com/",
    image: "https://pbs.twimg.com/media/DCFZJjSUAAARwN9.jpg",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Representing over 50 local, family farms, the Apple Hill Growers are dedicated to supporting agriculture in our community.  Founded in 1964 with just 16 apple ranches, we’ve now grown to include unique fruit & veggie farms, wineries, B&Bs, flower gardens, Christmas tree farms, and even a day spa. Our winding roads and scenic beauty have been a popular destination for over 50 years.   Come enjoy the fruits of our Apple Hill Growers any time of year!"
  },
  {
    title: "Sacramento River Delta",
    city: "Sacramento, CA",
    link: "https://visitcadelta.com/",
    image: "http://deltacalifornia.com/wp-content/uploads/2016/12/historicDelta1-1.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: false,
    description: "Just minutes from the city of Sacramento, the delta area feels like a million miles away from busy city life. Wandering along scenic Highway 160 throughout the southern portion of Sacramento County, the Delta area is rich in history and folklore. Whether you're exploring islands, fishing, swimming or enjoying a picnic with your family, you'll notice the pace of life slows as you enter this beautiful and majestic world. From fall through spring, it is a quiet getaway for people in search of back-road adventures and towns that haven't changed in 50 years. In summer, the waterways become full of people enjoying boating, waterskiing, and windsurfing. "
    
  },
  {
    title: "Sacramento Zoo",
    city: "Sacramento, CA",
    link: "https://www.saczoo.org/",
    image: "https://www.daytrippen.com/wp-content/uploads/2014/11/sacramento-zoo-train.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "The Sacramento Zoo inspires appreciation, respect and a connection with wildlife and nature through education, recreation and conservation. A few of the programs we offer are: summer camp, family and group overnights, ZooMobile, wildlife stage shows, keeper chats, zoo previews, animal encounters and much more."
  },
  {
    title: "Fairytale Town",
    city: "Sacramento, CA",
    link: "https://www.fairytaletown.org/",
    image: "https://www.fairytaletown.org/wp-content/uploads/2018/10/1-Humpty-Dumptys-Bridge.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "For 60 years, Fairytale Town has offered children and families a safe place to imagine, play and learn. With 26 playsets based on nursery rhymes and fairytales, a friendly flock of farm animals, two performing arts stages and several gardens, learning has never been more fun!"
  },
  {
    title: "SeaQuest Folsom",
    city: "Sacramento, CA",
    link: "https://folsom.visitseaquest.com/",
    image: "https://kncifm.com/wp-content/uploads/sites/6/2018/03/GettyImages-842398218.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "SeaQuest is a complete hands-on, interactive experience - not only with animals, but also with the community. SeaQuest strives to be an integral part of nearby neighborhoods by supporting local nonprofits, hosting field trips for kids, educating students of all ages and even acting as a tropical pet rescue for animals."
  },
  {
    title: "California State Railroad Museum",
    city: "Sacramento, CA",
    link: "https://www.californiarailroad.museum/",
    image: "https://www.californiabeaches.com/wp-content/uploads/2016/05/california-sacramento-state-railway-museum-1.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Experience the feats of engineering and ingenuity that have kept the Golden State steaming along for nearly 200 years – from immaculately restored engines and cars to exciting events and exhibits that bring the railroad to life."
  },
  {
    title: "Crocker Art Museum",
    city: "Sacramento, CA",
    link: "https://www.crockerart.org/",
    image: "https://cdn.carmel-apartments.com/system/uploads/fae/image/asset/5008/1600x1040-discover-enchanting-artwork-at-the-crocker-art-museum-in-sacramento.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "With art ranging from European drawings and Native American ceramics to California paintings and Chinese tomb figures, there is much to discover. If you are hoping to see the whole museum in one visit, we recommend you allow for at least three hours."
  },
  {
    title: "Sacramento Historic River Cruise",
    city: "Sacramento, CA",
    link: "https://www.hornblower.com/sacramento/sacramento-historic-river-cruises/",
    image: "https://my.hornblower.com/assets/images/products/hbsac/ec793343-50c7-4a5b-8f70-b9cfc5233a17.jpeg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "In this Sacramento river cruise, we’ll sail past Old Sacramento's famous historical sites, including the Delta King, the I Street Bridge, the Tower Bridge, and the Air Force Docks. As we tour, we’ll hear fascinating stories—from John Sutter, the founder of Sacramento to the wild days of the Gold Rush. California's capital city is filled with lively history and beautiful sights, and you’ll have the perfect view on this cruise. "
  },
  {
    title: "Capitol Park",
    city: "Sacramento, CA",
    link: "https://www.visitsacramento.com/listing/capitol-park/3764/",
    image: "https://live.staticflickr.com/4123/4935559470_23bb92b068_b.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "This popular park, surrounding the California State Capitol, has trees from around the world and memorials to significant state events."
  },
  {
    title: "Mix Downtown",
    city: "Sacramento, CA",
    link: "https://mixdowntown.net/",
    image: "https://d1hx7mabke4m1h.cloudfront.net/venue/image/7e21/mix.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "This small plates restaurant and lounge creates an inviting social scene with a rooftop patio featuring fire pits and spacious bars, an intimate dance floor, plush lounge seating, expansive couches and semi-private booths."
  },
  {
    title: "Badlands",
    city: "Sacramento, CA",
    link: "https://www.badlandssac.com/",
    image: "http://vp.cdn.cityvoterinc.com/GetImage.ashx?img=00/00/00/02/22/98/22298-2730724.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Badlands is Sacramento’s Premier LGBT Nightclub, Voted #1 LGBT Bar 8 Years in a Row!"
  },
  {
    title: "Sac Brew Boat",
    city: "Sacramento, CA",
    link: "https://www.sacbrewboat.com/",
    image: "https://media-cdn.tripadvisor.com/media/photo-s/13/f3/07/d2/bring-your-own-beer-cider.jpg",
    ages: 2,
    duration: 0,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: true,
    description: "Sacramento’s 16 passenger Brew Boat provides 1.5 hour pedal-powered party boat tours on the Sacramento River. Groups can bring their own beer/cider/wine aboard the chartered boat (limit 3 drinks per guest) as we cruise, pedal, and have fun on the river."
  },
  {
    title: "Riot Fest 15 Years",
    city: "Chicago, IL",
    link: "https://riotfest.org/chicago/lineup/",
    image: "https://www.jambase.com/wp-content/uploads/2019/05/riot-fest-2019-logo.jpg",
    ages: 2,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "The 2019 Riot Fest will be held at Douglas Park in Chicago, IL on September 13-15. Here’s the artists set to perform: The 2019 Riot Fest will be held at Douglas Park in Chicago, IL on September 13-15. Here’s the artists set to perform: Blink-182, Slayer (final Chicago/Milwaukee show), Bikini Kill, The Racounters, Rise Against, The Flaming Lips (performing “Yoshimi Battles The Pink Robots“), Jawbreaker, Ween (performing “The Mollusk“), Bloc Party (performing “Silent Alarm“), Die Antwoord, Patti Smith And Her Band, Taking Back Sunday (performing “Tell All Your Friends“/”Louder Now“), Rancid, Violent Femmes, Descendents, Manchester Orchestra and many more…"
  },
  {
    title: "Lincoln Park Zoo",
    city: "Chicago, IL",
    link: "https://www.lpzoo.org/dessert-fest-zoo",
    image: "https://www.lpzoo.org/sites/default/files/df_newsm.png",
    ages: 0,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: true,
    description: "Taste some of the best desserts in Chicago while taking in views of the zoo’s amazing animals and gardens. And don’t forget the champagne, beer, and wine (for those of age)! Tickets include admission, dessert tastings from some of Chicago's most famous bakeries, interactive games, live entertainment, giveaways, and more! A large portion of the proceeds will benefit Lincoln Park Zoo, helping to keep the zoo free and open to all 365 days a year. Be a party animal while support the animals! Get your tickets now!  6:30–11 p.m. Discounted early bird tickets available All ages"
  },
  {
    title: "Taste of Polonia Festival",
    city: "Chicago, IL",
    link: "https://topchicago.org/",
    image: "https://topchicago.org/wp-content/uploads/2019-TOP-FESTIVAL-GROUNDS-MAP.jpg",
    ages: 0,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "This annual Labor Day weekend taste fest in Chicago offers non-stop LIVE MUSIC, food, and fun for four days.  It’s a must-do family event with enough scheduling to keep both little kids & adults happy. The Taste of Polonia Festival is a popular one-of-a-kind food festival in Chicago because of all the added entertainment."
  },
  {
    title: "OktoberFest",
    city: "New York, NY",
    link: "https://www.eventbrite.com/e/oktoberfest-nyc-2019-at-watermark-tickets-59949067274",
    image: "http://www.downtownmagazinenyc.com/wp-content/uploads/2016/09/Watermark-Oktoberfest-Weekend-1-9951-copy.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Includes: 5 Food/Beer Tickets Priority Access With Online Package Purchase One ticket costs $10 One ticket includes one beer or one food item Giant Pretzel is 2 tickets To fill a large stein is 2 tickets Food/Beer Tickets can be used any date of the event"
  },
  {
    title: "Minnewaska State Park-Sams Point Area",
    city: "Minnewaska, NY",
    link: "https://www.alltrails.com/us/new-york/backpacking",
    image: "https://www.hikeformentalhealth.org/wp-content/uploads/2015/07/Sams-Point-Preserve-01.jpg",
    ages: 1,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "Explore the most popular Backpacking trails in New York with hand-curated trail maps and driving directions as well as detailed reviews and photos from hikers, campers and nature lovers like you."
  },
  {
    title: "Club Getaway",
    city: "Minnewaska, NY",
    link: "https://events.com/r/en_US/registration/club-getaway---fall-finale-2019-kent-october-757980",
    image: "https://d3emaq2p21aram.cloudfront.net/media/cache/venue_roundup_single_image_flex/uploads/%200Regular_Roundup/NYCorporate2017/ClubGetaway-01.jpg",
    ages: 2,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "Join us for our End of Season FALL FINALE!! Filled with mulled cider, pumpkin carving, hayrides, apple pie making, Touch Football games, haunted house and themed costume Party, this is the BEST way to kick off your fall celebrations.tember to help you schedule all the happenings you don’t want to miss like some of the best things to on Labor day, the West Indian Day Parade, and the one of the best NYC street fairs: Atlantic Antic. Sure, summer is nearly over, but the warm-weather isn’t going anywhere anytime soon. So make sure to enjoy all of the wonderful things to outside in New York before the cold front sweeps in!"
  },
  {
    title: "The National 9/11 Memorial & Museum",
    city: "New York, NY",
    link: "https://www.911memorial.org/",
    image: "https://www.911memorial.org/sites/default/files/jl_thinc_03hpcrop.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "The Museum’s 110,000 square feet of exhibition space is located within the archaeological heart of the World Trade Center site – telling the story of 9/11 through multimedia displays, archives, narratives and a collection of monumental and authentic artifacts. The lives of every victim of the 2001 and 1993 attacks are commemorated as visitors have the opportunity to learn about the lives of the men, women and children who died"
  },
  {
    title: "Niagara Falls",
    city: "Niagara Falls, NY",
    link: "https://www.niagarafallsstatepark.com/plan-your-trip/more-to-do",
    image: "https://www.niagarafallsstatepark.com/~/media/parks/niagara-falls/homepage/banner-niagara1.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "If you are driving to Niagara Falls, NY, there are several ways to access the park and plenty of parking options. With four lots at the Park and several city lots just footsteps from the Park, you will be ready to start your Niagara Falls adventure just as soon as you get out of the car!"
  },
  {
    title: "Statue of Liberty",
    city: "New York, NY ",
    link: "https://www.nps.gov/stli/index.htm",
    image: "https://freetoursbyfoot.com/wp-content/uploads/2018/04/Statue-of-Liberty-Ticket-Options.jpg",
    ages: 1,
    duration: 1,
    location: 1,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "The Statue of Liberty Enlightening the World was a gift of friendship from the people of France to the United States and is recognized as a universal symbol of freedom and democracy. The Statue of Liberty was dedicated on October 28, 1886.  It was designated as a National Monument in 1924.  Employees of the National Park Service have been caring for the colossal copper statue since 1933."
  },
  {
    title: "Jersey Boys concert",
    city: "New York, NY ",
    link: "http://www.jerseyboysinfo.com/newyork/",
    image: "http://www.jerseyboysinfo.com/img/header.png",
    ages: 2,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "They were just four guys from Jersey, until they sang their very first note. They had a sound nobody had ever heard… and the radio just couldn’t get enough of. But while their harmonies were perfect on stage, off stage it was a very different story -- a story that has made them an international sensation all over again.  Go behind the music and inside the story of Frankie Valli and The Four Seasons in the Tony Award®-winning true-life musical phenomenon, JERSEY BOYS. From the streets of New Jersey to the Rock and Roll Hall of Fame, this is the musical that’s just too good to be true."
  },
  {
    title: "Central Park Bike rental ",
    city: "New York, NY ",
    link: "https://bikerentalcentralpark.com/",
    image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-540x360/06/75/c4/be.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: false,
    description: "Ride through the world’s most famous urban park and experience New York in a completely unique and exhilarating way.  Our bikes will help you see Central Park like you never could on foot.  See everything from the incredible Olmstead designed waterfalls, pool, and loch to the famous Metropolitan Museum of Art. A perfect blend of movie scenes, classic architecture, historical attractions, celebrity sightings, and so much more! We make it easy to get your bike and get the most from your time in the park."
  },
  {
    title: "Harry Potter and the Cursed child on Broadway.",
    city: "New York, NY ",
    link: "https://www.harrypottertheplay.com/us/#",
    image: "https://www.harrypottertheplay.com/us/content/themes/tt-broadway/build/images/DUMBLEDORE.png",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 2,
    approved: true,
    description: "Leaves you gasping in wonder at the magic of it all! - TIME Magazine  Unprecedented stagecraft.  Thrilling storytelling.  Magic like you've never seen on stage."
  },
  {
    title: "Standard Central Park Horse Carriage Ride",
    city: "New York, NY ",
    link: "https://www.centralpark.com/tours/horse-carriage-rides",
    image: "https://previews.123rf.com/images/americanspirit/americanspirit1306/americanspirit130609908/20491612-horse-carriage-ride-in-central-park-manhattan-new-york-city-ny-after-winter-snowstorm.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Horse-drawn carriages are a unique and historical way to experience the beauty of Central Park. Visit well-known attractions like Belvedere Castle, Strawberry Fields, Bethesda Fountain and the Mall. Customized rides for weddings, proposals, birthdays, anniversaries, and other special occasions."
  },
  {
    title: "Macy's Thanksgiving Day Parade",
    city: "New York, NY ",
    link: "https://www.macys.com/social/parade/",
    image: "https://www.usmagazine.com/wp-content/uploads/2018/11/macys-thanksgiving-day-parade-2.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "The most amazing parade.  Entertainment and the newest ballons.  Magic of past parades-discover our proud history.."
  },
  {
    title: "New York International Auto Show",
    city: "New York, NY ",
    link: "https://www.autoshowny.com/",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/NY_Auto_Show_2013.JPG/1200px-NY_Auto_Show_2013.JPG",
    ages: 1,
    duration: 1,
    location: 1,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "The New York International Auto Show is easy to get to from anywhere in the tri-state area. There are many parking facilities in the area, plus mass transit (Metro North, LIRR, NY Waterway Ferry, Subways and Buses)."
  },
  {
    title: "Free Sunrise Yoga at Riverside",
    city: "New Orleans, LA",
    link: "https://www.neworleans.com/event/free-sunrise-yoga-at-riverwalk/18558/",
    image: "https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_251,q_50,w_380/https://assets.simpleviewinc.com/simpleview/image/upload/crm/neworleans/yoga0_98636d31-5056-b365-ab93058c01dd09ed.png",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Yoga will be held inside the mall near the Julia Street entrance, or if weather permits, on the balcony overlooking the scenic Mississippi River. Guests are encouraged to bring a mat, a water bottle, and any other preferred personal yoga equipment. Guests will receive a free parking pass at the end of the class. Donations to @jaibhaktiyoga are greatly appreciated."
  },
  {
    title: "SAINTS KICKOFF RUN Presented by Chevron",
    city: "New Orleans, LA",
    link: "https://saints5k.com/",
    image: "https://saints5k.com/wp-content/uploads/2019/07/slider2.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "The 2019 SAINTS KICKOFF RUN is back for its 8th year! New this year... the race will START on the field at the 50-yard line inside the Mercedes-Benz Superdome and FINISH in Champions Square! PARTICIPANT PERKS Start the Kickoff 5K Run inside the Mercedes-Benz Superdome at 7:30am"
  },
  {
    title: "XXL: The Party",
    city: "New Orleans, LA",
    link: "http://www.neworleans.me/events/detail/56448/XXL-The-Party-Southern-Decadence-2018-The-Phoenix",
    image: "http://1c07472a2b0b5051877b-369541f6841b187579f8311c0d8cb986.r22.cf1.rackcdn.com//production/uploads/photo/file/76237/img_490x0_37220780_10160672192460261_1976879618493251584_o.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "You ready for some fun in the hot, steamy swamp? What adventures await you on the bayou? On Sunday, September 2, from 2 to 5 p.m., we close the entire bar for the most exclusive private party of Southern Decadence. We are proud to welcome Atlas Grant and Bennett Anthony for XXL: The Party. Only a limited number of tickets will be available. This event has sold out each year. Don’t delay! Enjoy an open bar for well cocktails and domestic beers. A coat check will be available. No refunds. No cell phones or cameras permitted."
  },
  {
    title: "Summer of Sustainability",
    city: "New Orleans, LA",
    link: "https://sustainablesummer.org/",
    image: "http://middlebrookcenter.com/elsee/wp-content/uploads/2013/06/08.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 2,
    approved: true,
    description: "Time to Dine with the Sharks! Audubon Nature Institute’s sustainable seafood program, Gulf United for Lasting Fisheries (G.U.L.F.,) is celebrating the bounty of the Gulf of Mexico all summer. Our annual Summer of Sustainability dinner series will be hosted at Audubon Aquarium of the Americas and features the chefs of the G.U.L.F. Chef Council and Restaurant Partnership Program."
  },
  {
    title: "Bayou Sauvage NWR Ridge Trail & Boardwalk",
    city: "New Orleans, LA",
    link: "https://www.fws.gov/refuge/Bayou_Sauvage/visit/plan_your_visit.html",
    image: "https://www.fws.gov/uploadedImages/Region_4/NWRS/Zone_1/Southeast_Louisiana_Refuges_Complex/Bayou_Sauvage/Images/512x219_egrets_bs_photo%20copyright_tom_carlisle.jpg?w=180&h=140&mode=crop",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Located just northeast of New Orleans, Bayou Sauvage National Wildlife Refuge is a marsh and wetland habitat rich in wildlife and recreation opportunities. The Refuge is a popular place to enjoy fishing, hiking, paddling, bird watching, nature photography, youth waterfowl hunting, self-guided tours, and interpretive and educational programs."
  },
  {
    title: "Congress Bridge Bats",
    city: "Austin, TX",
    link: "https://www.austintexas.org/things-to-do/outdoors/bat-watching/",
    image: "https://d3qvqlc701gzhm.cloudfront.net/full/65e346558e598b6040ffd4952057720fb39239b04a1153cfaf41653f22f91d55.jpg",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "A 1980 renovation transformed the Congress Avenue Bridge into an ideal bat cave, soon attracting migrating Mexican free-tailed bats. Decades later, Austin's bat numbers have swelled and locals have adopted the beloved creatures as neighbors who happily handle the city's bug mitigation and provide an amazing nightly show."
  },
  {
    title: "Your Biker Gang",
    city: "Austin, TX",
    link: "https://yourbikergang.com/book-austin/",
    image: "http://www.videocityguide.com/sites/blog_vcg/thingstodo/your_biker_gang_2.jpg",
    ages: 1,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Most memorable experience in Austin! Join our professional guide and see Austin like you have never seen it before. Amazing experience for family, friends, couples or coworkers.  If you are looking for one of the funnest things to do in Austin.  Hit the brakes right here!  You've found it.  A Texas exclusive that's sure to be the most memorably activity you'll do here."
  },
  {
    title: "Live Love Paddle",
    city: "Austin, TX",
    link: "https://www.livelovepaddle.com/",
    image: "https://www.livelovepaddle.com/assets/images/gallery/g7.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: true,
    description: "Spend an evening kayaking or paddle boarding to a secluded island on Lady Bird Lake under the light of a full moon! On the island, you will be treated to a live music acoustic set from Jeremy Booth and the Wanderers, a sunset from the water, a campfire, and s'mores! This is as local Austin as Austin gets! We recommend you bring a blanket or small camp chair and bug spray. This is a BYOB event, small collapsible coolers work best."
  },
  {
    title: "Old New Orleans Rum Distillation",
    city: "New Orleans, LA",
    link: "https://oldneworleansrum.com",
    image: "https://oldneworleansrum.com/wp-content/uploads/2019/08/products-edit.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "We are the art of celebration. A community of committed people creating great drinks to honor the world. Through fresh, natural ingredients, know-how and the will to make and share our art, we create joy in a bottle."
  },
  {
    title: "Platinum Limousine Wine Tours",
    city: "Sacramento, CA",
    link: "https://www.platinumlimosac.com/",
    image: "http://d14ig7mai3qkk7.cloudfront.net/platinumlimosac/wine-tour.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "When you’re out with us on a limousine wine tour, we know the best wineries and the best spots for lunch. We’ll tailor your itinerary to your personal tastes. Let us show you the wineries of Napa, Sonoma, Amador, Lodi or El Dorado. There’s no better way to make the day enjoyable—and relaxing—than with a chauffeured limo from Platinum Limousine. Be the envy of everyone in the tasting room when you pull up in an elegant limousine. With multiple HD screens and high-end sound system, your party will be cruising in style"
  },
  {
    title: "Chicago Wine Tasting Cruise",
    city: "Chicago, IL",
    link: "https://www.wendellaboats.com/schedule-tickets/",
    image: "https://cdn.getyourguide.com/img/tour_img-716617-148.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: false,
    description: "Relax with a glass of wine and take in the evening views of the Chicago skyline! Enjoy sweet and savory wine and cheese pairings from Pastoral while cruising Lake Michigan and the Chicago River. Must be 21+."
  },
  {
    title: "Austin Wine Tours",
    city: "Austin, TX",
    link: "https://winetoursaustintx.com/",
    image: "http://www.videocityguide.com/sites/blog_vcg/thingstodo/austinwinetours.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 2,
    approved: true,
    description: "Austin marks the beginning of the Texas hill country where arid weather, small valleys, and micro climates are home to a handful of excellent vineyards that give Napa Valley a run for its money. The team at Austin Wine Tours will arrange tours to a select group of top vineyards complete with transportation and a few inside touches to make for a delightful afternoon/evening that boasts hints of black pepper, bold charisma, and stylish sophistication."
  },
  {
    title: "Circuit of the Amerca's COTA Karting",
    city: "Austin, TX",
    link: "http://www.circuitoftheamericas.com/karting",
    image: "http://ea80e97cace747c2c244-5483548c70a81fe49af7816b21fff1c8.r64.cf1.rackcdn.com/track-rental1_180220_124002.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "It's hard to make the F1 circuit but you'll never know if you've got what it takes unless you get behind the wheel. Circuit of the Americas now offers a Karting experience that is out of this world! With karts that go up to 55mph and a track that features 15 turns, this is an exceptional way to see the one and only F1 track in the United States."
  },
  {
    title: "Barton Creek Greenbelt",
    city: "Austin, TX",
    link: "https://austinparks.org/barton-creek-greenbelt/",
    image: "https://assets3.thrillist.com/v1/image/1746225/size/tmg-article_default_mobile;jpeg_quality=20.jpg",
    ages: 1,
    duration: 2,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: true,
    description: "Starting at Barton Springs Pool, the Barton Creek Greenbelt is one of Austin's best treasures with areas known as the Flats, Twin Falls, and Sculpture Falls.  The Flats is known to host large gatherings, even the occasional drum circle. Twin Falls offers one of the better waterfalls, and Sculpture Falls is known for a little solitude. There's also great rock climbing, mountain biking, hiking, and other outdoor activities that appeal to a wide array of outdoorsy types. It's best when the water if flowing, even if it's low just 15 - 20 cfs. You can check out a flow gauge at Loop 360 bridge here."
  },
  {
    title: "Inner Space Cavern",
    city: "Austin, TX",
    link: "https://innerspacecavern.com/",
    image: "https://www.theflashlist.com/assets/venues/usa/tx-texas/central/georgetown/living/recreation/caves/inner-space-cavern/images/InnerSpaceCavern-Interior-AustinCameraGuy-1000.jpg",
    ages: 1,
    duration: 1,
    location: 1,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "Located about 25 north of Austin lies Inner Space Caverns. You and your friends, family, or crew can tour below the ground and explore a natural cavern formed millions of years ago beneath one of Texas' busiest interstate highways. Inner Space Cavern is filled with history, mystery and chemistry! This all season activity caters to large groups and offers one of the most engaging afternoon activities in Texas."
  },
  {
    title: "California Academy of Sciences",
    city: "Sacramento, CA",
    link: "https://www.calacademy.org/nightlife/fermented-nightlife",
    image: "https://s3-media1.fl.yelpcdn.com/bphoto/kYwAj-TMFeMzHHXj8gceRA/348s.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Enjoy music, creatures, and cocktails as you set out with friends on a journey to the stars and the depths of the sea. Featuring a new theme each week, after-hours access to all exhibits, and special programming, NightLife is your ticket to the nocturnal side of the Academy."
  },
  {
    title: "Urbon Cow Half Marathon",
    city: "Sacramento, CA",
    link: "https://www.urbancowhalf.com/",
    image: "http://nextbib.s3.amazonaws.com/photos/files/000/000/196/large/14.jpg?1415152855",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 1,
    approved: true,
    description: "From Raceroster.com: Urban Cow Half Marathon, 2-Person Relay & 5K William Land Park, Land Park Drive, Sacramento, California, United States - You've herd about Urban Cow! You've seen the bumper… - October 6, 2019"
  },
  {
    title: "Effie Yeaw Nature Center",
    city: "Sacramento, CA",
    link: "https://www.sacnaturecenter.net/",
    image: "https://www.sacnaturecenter.net/images/trails.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "Effie Yeaw Nature Center is located in low rolling hills on the banks of the bubbling American River. In addition to  the Maidu village (an outdoor display of local Native American culture, including a grinding rock), the park offers nature talks with resident animal experts on weekends and is home to plenty hiking trails that lead down to the river where, in fall months, you may see salmon returning to spawn. No matter the season, you’re sure to spot deer, woodpeckers and wild turkeys."
  },
  {
    title: "Nor Cal Bats Sighting",
    city: "Sacramento, CA",
    link: "http://norcalbats.org/",
    image: "http://norcalbats.org/wp-content/uploads/2017/12/BAT_Mexican_Free_tailed.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Learn about these animals and their importance as insect control. Inform others and help protect our natural world. Dispel misconceptions and save these highly valuable mammals with education and rescue."
  },
  {
    title: "Playland Skate Center",
    city: "Austin, TX",
    link: "https://playlandskatecenter.net/",
    image: "https://public-realtyaustin.netdna-ssl.com/resources/Images/realty-austin-indoor-activities-grab-your-skates.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Playland Skate Center offers the finest in skating entertainment with an impressive light show, fog machine and state of the art sound system playing a wide variety of music."
  },
  {
    title: "The Escape Game",
    city: "New Orleans, LA",
    link: "https://theescapegame.com",
    image: "https://booking.theescapegame.com/slir/h500/https://booking.theescapegame.com/media/experiences/5b7ee72de2ac9ff56e8b456b.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: false,
    description: "There are plenty of action-packed adventures for the adrenaline junkie in New Orleans! iFLY is where the dream of flight becomes a reality and a part of something bigger than yourself. K1 Speed offers highly-advanced and environmentally-friendly electric go-karts as well as authentic racing memorabilia, pit cafes, meeting rooms and pool tables, perfect for a place to visit with family and friends or place to host a corporate event or party! Or you and a group of friends or coworkers can solve a series of puzzles using deduction skills and clues all while locked in a room and only having 60 minutes to escape at The Escape Game and Panic Room!"
  },
  {
    title: "The Escape Game",
    city: "Chicago, IL",
    link: "https://theescapegame.com",
    image: "https://booking.theescapegame.com/slir/h500/https://booking.theescapegame.com/media/experiences/5b7ee72de2ac9ff56e8b456b.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "There are plenty of action-packed adventures for the adrenaline junkie in Chicago! iFLY is where the dream of flight becomes a reality and a part of something bigger than yourself. K1 Speed offers highly-advanced and environmentally-friendly electric go-karts as well as authentic racing memorabilia, pit cafes, meeting rooms and pool tables, perfect for a place to visit with family and friends or place to host a corporate event or party! Or you and a group of friends or coworkers can solve a series of puzzles using deduction skills and clues all while locked in a room and only having 60 minutes to escape at The Escape Game and Panic Room!"
  },
  {
    title: "The Escape Game",
    city: "New York, NY",
    link: "https://theescapegame.com",
    image: "https://booking.theescapegame.com/slir/h500/https://booking.theescapegame.com/media/experiences/5b7ee72de2ac9ff56e8b456b.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "There are plenty of action-packed adventures for the adrenaline junkie in New York! iFLY is where the dream of flight becomes a reality and a part of something bigger than yourself. K1 Speed offers highly-advanced and environmentally-friendly electric go-karts as well as authentic racing memorabilia, pit cafes, meeting rooms and pool tables, perfect for a place to visit with family and friends or place to host a corporate event or party! Or you and a group of friends or coworkers can solve a series of puzzles using deduction skills and clues all while locked in a room and only having 60 minutes to escape at The Escape Game and Panic Room!"
  },
  {
    title: "The Escape Game",
    city: "Austin, TX",
    link: "https://theescapegame.com",
    image: "https://booking.theescapegame.com/slir/h500/https://booking.theescapegame.com/media/experiences/5b7ee72de2ac9ff56e8b456b.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "There are plenty of action-packed adventures for the adrenaline junkie in Austin! iFLY is where the dream of flight becomes a reality and a part of something bigger than yourself. K1 Speed offers highly-advanced and environmentally-friendly electric go-karts as well as authentic racing memorabilia, pit cafes, meeting rooms and pool tables, perfect for a place to visit with family and friends or place to host a corporate event or party! Or you and a group of friends or coworkers can solve a series of puzzles using deduction skills and clues all while locked in a room and only having 60 minutes to escape at The Escape Game and Austin Panic Room!"
  },
  {
    title: "Austin City Limits Music Festival",
    city: "Austin, TX",
    link: "https://www.aclfestival.com/",
    image: "https://austinot.com/wp-content/uploads/2016/10/acl-entrance-at-dusk-1024x683.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 2,
    approved: true,
    description: "The Austin City Limits Music Festival is an annual music festival held in Zilker Park in Austin, Texas on two consecutive three-day weekends. Inspired by the KLRU/PBS music series of the same name, the festival is produced by Austin-based company C3 Presents, which also produces Lollapalooza"
  },
  {
    title: "Austin Speed Dating",
    city: "Austin, TX",
    link: "https://docbsrestaurant.com/locations/austin/",
    image: "https://onspeeddating.com/images/about/AboutUs.png",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "From signature Cocktails to speed dating.  Doc B's has fun for your style"
  },
  {
    title: "Friends of River Place Trail",
    city: "Austin, TX",
    link: "http://friendsofriverplacetrail.com/",
    image: "http://friendsofriverplacetrail.com/wp-content/uploads/2015/04/2012-09-29-21.38.45.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "We have three trails in the River Place Neighborhood:  Little Fern, Canyon, and Panther Hollow. The trails all converge at Panther Junction."
  },
  {
    title: "LakeTravis",
    city: "Austin, TX",
    link: "https://laketravis.com/top-5-things-to-do-on-lake-travis/",
    image: "https://laketravis.com/listify/wp-content/uploads/2016/10/oasis-11-1.jpg",
    ages: 0,
    duration: 2,
    location: 1,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "We’ve looked at our site analytics. We’ve found the Top 5 things to do on Lake Travis ranked by pageviews. We’ve said it before, Lake Travis is a BIG lake. It’s 63.75 miles long, has over 271 miles of shoreline. It’s also the the most commercially active reservoir in the state. It’s crystal clear blue waters, it’s proximity to Austin proper and it’s status as a non Corps of Engineers lake (allowing private lakeside property), have it number one, by a long shot, in available recreation activities and lake related businesses. While Austin locals eventually find and bookmark the “go to” spots and activities on the lake, we find may prospective visitors are almost overwhelmed by the options (and the options within options) available for fun on Lake Travis."
  },
  {
    title: "Rhythm of the Water: Whisky",
    city: "Austin, TX",
    link: "https://simsfoundation.org/events/",
    image: "https://foodanddrink.scotsman.com/wp-content/uploads/2017/06/11500-SS_thomas-telford-bridge-craigellachie_158387885-7-750x400.jpg",
    ages: 2,
    duration: 2,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Live music is the heart and soul of Austin, but living as a musician can be a real challenge. Musicians and music professionals are at higher risk for mental illness and substance abuse, working under the stress of an unstable income, a skyrocketing cost of living, erratic tour schedules, distance from family and support, and constant proximity to drugs and alcohol."
  },
  {
    title: "Mayfield Nature Preserve",
    city: "Austin, TX",
    link: "https://mayfieldpark.org/",
    image: "https://mayfieldpark.org/wp-content/uploads/2015/05/MP_PeacockFan-960x332.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 2,
    price: 0,
    approved: true,
    description: "Don’t be surprised if you feel a little underdressed when you arrive at the mouth of the trailhead: The historic cottage and wandering peacocks make Mayfield a popular wedding destination. But walk past the frequent parties and there are 24 acres to explore, including a path that takes you down to a dock overlooking Lake Austin and several small lily ponds filled with turtles. Be warned that this hike isn’t going to build up your quads. But if you are looking to unwind after a stressful week, it can’t be beat."
  },
  {
    title: "Austin Zoo",
    city: "Austin, TX",
    link: "https://austinzoo.org",
    image: "https://austinzoo.org/wp-content/uploads/2017/12/Tiger-e1512597132163.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "The mission of Austin Zoo is to assist animals in need through rescue, rehabilitation and education.  Located on the southwest edge of Austin off Highway 290 West and Circle Drive, Austin Zoo is a pleasant Hill Country zoo where visitors from around the world can come to learn about animals close-up, spend some time outdoors getting exercise, and have fun.."
  },
  {
    title: "Museum of the Weird",
    city: "Austin, TX",
    link: "https://www.museumoftheweird.com/",
    image: "https://pm1.narvii.com/6792/8cc34afc5ce950073d99cd2a9bb2bfe51b47d517v2_hq.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "In the heart of Austin's famous Sixth Street lies the city's most curious and mysterious gift shop.  In the back of the shop is what some call Austin's best kept secret..."
  },
  {
    title: "Murder Walk",
    city: "Austin, TX",
    link: "https://www.touratx.com/",
    image: "http://48tx1q1rrcysi4t7l687xbtt.wpengine.netdna-cdn.com/wp-content/uploads/chapel-default.jpg",
    ages: 2,
    duration: 1,
    location: 1,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Austin's (true crime) walking tour! The Murder Walk Austin tour will begin on June 7, 2019. This tour is only offered on Fridays and Saturdays. This tour will depart at 8:00 pm from the intersection of Bowie and West 6th,  at the corner of Whole Foods in downtown Austin, Texas. "
  },
  {
    title: "Audubon Nature Zoo",
    city: "New Orleans, LA",
    link: "https://audubonnatureinstitute.org/tickets",
    image: "https://audubonnatureinstitute.org/images/600x450/aquarium/iguana-girl-600.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Located in historic Uptown New Orleans Audubon Zoo offers an exotic mix of animals from around the globe, engaging educational programs, hands-on animal encounters and lush gardens. Unique natural habitat exhibits such as the award-winning Louisiana Swamp and Jaguar Jungle showcase the relationship between people and nature. Don't miss the daily animal presentations, chats and feeds; our highly endangered whooping cranes, Amur leopards, and orangutans; our tiger; and our mysterious white alligators. Audubon Zoo is often ranked among the country's best for innovation and entertainment value!.  Gets hot out visit the Cool Zoo.."
  },
  {
    title: "Audubon Aquairum",
    city: "New Orleans, LA",
    link: "https://audubonnatureinstitute.org/aquarium/explore-aquarium",
    image: "http://naturally-glam.com/wp-content/uploads/2017/08/Audubon-Aquarium-New-Orleans_03.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Located on the Mississippi River adjacent to the French Quarter Audubon Aquarium of the Americas immerses you in an underwater world. The colors of the Great Maya Reef come alive in our walk-through tunnel, while our penguins and Southern sea otters are visitor favorites. Touch a stingray, feed a parakeet, and marvel at our gigantic sharks and rays in the 400,000-gallon Gulf of Mexico Exhibit. Watch for sea turtles throughout the Aquarium as coordinator of the Louisiana Marine Mammal and Sea Turtle Rescue Program, we prepare many of them for release to the wild."
  },
  {
    title: "French Quarter Tour",
    city: "New Orleans, LA",
    link: "https://www.frenchquarterkidstours.com/",
    image: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_800,q_75,w_640/v1/clients/neworleans/NOTMC_49353_d4610c3e-6118-4851-b2dd-1e3b940601f9.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "Located on the Mississippi River adjacent to the French Quarter Audubon Aquarium of the Americas immerses you in an underwater world. The colors of the Great Maya Reef come alive in our walk-through tunnel, while our penguins and Southern sea otters are visitor favorites. Touch a stingray, feed a parakeet, and marvel at our gigantic sharks and rays in the 400,000-gallon Gulf of Mexico Exhibit. Watch for sea turtles throughout the Aquarium as coordinator of the Louisiana Marine Mammal and Sea Turtle Rescue Program, we prepare many of them for release to the wild."
  },
  {
    title: "New Orleans Historic Voodoo Museum",
    city: "New Orleans, LA",
    link: "https://www.voodoomuseum.com/",
    image: "https://www.voodoomuseum.com/img/portfolio/fullsize/1.jpg",
    ages: 1,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Serving the New Orleans community since 1972 and bringing you a casual and curious experience intended to preserve the legacy of New Orleans' Voodoo history and culture while educating and entertaining visitors."
  },
  {
    title: "St Louis Cemetery #1",
    city: "New Orleans, LA",
    link: "https://www.frenchquarter.com/st-louis-cemetery-no-1/",
    image: "https://www.frenchquarter.com/wp-content/uploads/2017/07/St.-Louis-Cemetery-No.-1_Overhead.jpg",
    ages: 1,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: false,
    description: "It’s no wonder St. Louis Cemetery attracts more than 100,000 visitors each year. Some come to leave offerings for Voodoo Queen Marie Laveau, while others come to tend the graves of loved ones interred within (St. Louis Cemetery remains an active gravesite). Still, others come to experience city’s living history via a stroll through its oldest cemetery (St. Louis Cemetery was built in 1789). Regardless of your motivation, a trip to New Orleans wouldn’t be complete without visiting St. Louis Cemetery No. 1."
  },
  {
    title: "Steamboat Natchez",
    city: "New Orleans, LA",
    link: "https://www.steamboatnatchez.com/",
    image: "https://pbs.twimg.com/media/DxqikzLXgAA_s6Q.jpg",
    ages: 1,
    duration: 0,
    location: 1,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "The New Orleans Steamboat Company locally owns and operates the last authentic Steamboat on the Mighty Mississippi River: The Steamboat NATCHEZ Dinner Jazz and Daytime jazz cruises … run daily, year round, in the style of authentic steamboats in New Orleans for centuries! Steam Engine Room visitation, calliope, live jazz and optional Creole food and local beverages. Come aboard and enjoy New Orleans hospitality….. Steamboat Style!"
  },
  {
    title: "French Quarter Attractions",
    city: "New Orleans, LA",
    link: "https://www.neworleans.com/plan/neighborhoods/french-quarter/attractions/",
    image: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_500,q_75,w_1400/v1/clients/neworleans/NOTMC_33705_274af993-542c-4115-892b-fddd34b0bae4.jpg",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "With so much culture, history and entertainment, you’ll find a unique and exciting experience around every corner with choices from museums, tours, riverboat rides and so much more."
  },
  {
    title: "SightSeeing New Orleans",
    city: "New Orleans, LA",
    link: "https://city-sightseeing.com/en/33/new-orleans/266/hop-on-hop-off-new-orleans?utm_source=google&utm_medium=cpc&gclid=Cj0KCQjwy97qBRDoARIsAITONTJFFe52ZAI1NCAuCrl5vaOIf2UeMaV1tnvzWbCx3A9KqVI9hTIP-NMaAjo4EALw_wcB",
    image: "https://www.bigeasy.com/uploads/images/CSS%20map.png",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Make your New Orleans adventure as remarkable as it can be. Take in the 19 diverse hop-off stops of this bus tour. You will be pleasantly surprised at the variety of attractions in the city and how it changes throughout your open-top bus trip, from the sensational stadium, to the magnificent War Museum - not to mention the grand Harrah's Casino. New Orleans really does have it all."
  },
  {
    title: "The National WWII Museum",
    city: "New Orleans, LA",
    link: "https://www.nationalww2museum.org",
    image: "https://www.nationalww2museum.org/sites/default/files/styles/wide_medium/public/2017-06/group_sales_campus_aerial.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "The National WWII Museum tells the story of the American experience in the war that changed the world—why it was fought, how it was won, and what it means today—so that all generations will understand the price of freedom and be inspired by what they learn."
  },
  {
    title: "Canoe & Trails Adventures",
    city: "New Orleans, LA",
    link: "https://www.canoeandtrail.com/",
    image: "https://media-cdn.tripadvisor.com/media/photo-s/07/ae/74/1e/canoe-and-trail-adventures.jpg",
    ages: 2,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 1,
    approved: true,
    description: "New Orleans Kayak Swamp Tours, Kayak Rentals, Moonlight Paddles & more Guided by Louisiana Master Naturalist. Most experienced guides in Louisiana.  45 Years of swamp tours have helped guest make memories that last a lifetime. "
  },
  {
    title: "New Orleans City Park",
    city: "New Orleans, LA",
    link: "https://neworleanscitypark.com/",
    image: "http://neworleanscitypark.com/images/content/cache/made/images/content/site/IMG_9010_1200_570_c1.JPG",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Stretching from Bayou St. John to Lake Pontchartrain, the 1,300-acre New Orleans City Park is one of Orleans Parish’s two green jewels. (The other is Audubon Park in Uptown.) The entire city united to restore the park after Hurricane Katrina shredded its landscaping, downing many of its 600-year-old live oaks. The cleanup is transcendent, with new walking and biking paths, a great lawn for concerts, and a revival of beloved attractions, such as Story Land and Carousel Gardens Amusement Park, that have entertained children since 1906. "
  },
  {
    title: "New Orleans: Early Evening Cocktail History Tour",
    city: "New Orleans, LA",
    link: "https://www.getyourguide.com/new-orleans-l370/new-orleans-cocktail-history-tour-t76234/?partner_id=34FAF&cmp=TTDNightNolaCocktailTour",
    image: "https://cdn.getyourguide.com/img/tour_img-1928897-145.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Join this tour through New Orleans’ historic and fascinating history of cocktails, and sample them along the way."
  },
  {
    title: "Night out at Marigny Brasserie",
    city: "New Orleans, LA",
    link: "https://www.fws.gov/refuge/Bayou_Sauvage/",
    image: "https://gonola.com/images/marigny-brasserie.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Going through Baton Rouge from New Orleans, it takes about an hour and 45 minutes to drive to this beautiful, one of a kind destination just over the Mississippi border.  This hiking trail features more than a half-doxen small water falls.  You can easily spend an entire day here, making this well worth your drive."
  },
  {
    title: "North Avenue Beach",
    city: "Chicago, IL",
    link: "https://www.chicagoparkdistrict.com/parks-facilities/north-avenue-beach",
    image: "https://patch.com/img/cdn20/users/22965241/20180620/031250/styles/raw/public/processed_images/volleywood_2-1529521962-7530.jpg",
    ages: 0,
    duration: 2,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "North Avenue Beach is situated in Lincoln Park and is one of the most popular beach destinations in Chicago. The beach features a unique beach house with over 22,000- square feet, which offers activities for all ages and some of the best views in Chicago. If you want to enjoy lunch on North Avenue Beach, head over to Castaways Bar and Grill for some seaside burgers, ice-cream and tasty beverages on their rooftop. You can rent bikes on the beach or step it up a notch and rent a wakeboard or paddleboard. Take a stroll among the different vendors selling clothes, sandals and other unique souvenirs."
  }, 
  {
    title: "Oak Street Beach",
    city: "Chicago, IL",
    link: "https://www.chicagoparkdistrict.com/parks-facilities/oak-street-beach",
    image: "https://assets3.thrillist.com/v1/image/1508587/size/tmg-venue_carousel_mobile.jpg",
    ages: 0,
    duration: 2,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Spend some time at Oak Street Beach and it’s easy to imagine you are actually in the Caribbean. The white sand beach and crystal clear waters make this the perfect place to swim, rent chairs or bikes, play volleyball and take in the magnificent views across the horizon. You can access the beach from 6:00 am to 11:00 pm – this is a great place to enjoy the sunset. You are only permitted to swim when the lifeguard is present between 11:00 am and 7:00 pm daily."
  },
  {
    title: "North Park Village Nature Center",
    city: "Chicago, IL",
    link: "https://www.chicagoparkdistrict.com/parks-facilities/north-park-village-nature-center",
    image: "https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_396,q_75,w_971/https://Chicago.simpleviewcrm.com/images/listings/original_88000-nparknature-140.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Call it a hidden gem, but this 155-acre escape is in walking (or should we say hiking) distance of the city. Seriously, when’s the last time you walked in an open meadow? Quiet paths, boardwalks, and some undisturbed woodland make this a serene hike that lasts about an hour or two."
  },
  {
    title: "Adults Night at the Trampoline Park",
    city: "Chicago, IL",
    link: "https://www.oronotrampoline.com/event/pass-holder-perk-3/",
    image: "https://tickets.mercurycruises.com/webstore/FrontEnd/mercury/img/mercury-family-home.jpg",
    ages: 2,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "With over 30,000 square feet of indoor trampolines and other attractions, Altitude Trampoline Park is jumping! We're giving you a shot to jump around with no kids! This event is 21+ only."
  },
  {
    title: "River and Lake Cruises",
    city: "Chicago, IL",
    link: "https://mercurycruises.com/tours/?gclid=Cj0KCQjwy97qBRDoARIsAITONTIsVlhH5z5j81-geLvrHL_uU65n0Yef-7oMeQQQbgNy7tYyB-zhm9MaApALEALw_wcB",
    image: "https://tickets.mercurycruises.com/webstore/FrontEnd/mercury/img/mercury-family-home.jpg",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Out on Lake Michigan and along the Chicago River you can sit back and give Chicago’s cityscape the attention it deserves. The Chicago River Architecture Cruise has a more sedate pace, and gives you a clear view of more than 40 listed landmarks, accompanied by live commentary from an expert guide."
  },
  {
    title: "Chicago SKY Deck",
    city: "Chicago, IL",
    link: "https://theskydeck.com/",
    image: "https://theskydeck.com/wp-content/uploads/2013/06/home-ledge.jpg",
    ages: 1,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "The 442-metre Willis Tower was the tallest building in the world for 25 years, and is is still among the top 25. With the Chicago Skydeck Experience Ticket, you can waste no time, skipping the line and speeding up to the Skydeck 412.4 metres above the west side of the Loop. On the meandering route to the elevator, there’s a movie detailing the 45-year history of the Willis Tower and Chicago’s other architectural wonders. After a swift ride you’ll be struck by a view extending over 50 miles and four states. The Ledge at the Skydeck will either give you a buzz or make your stomach flutter: This is a set of four all-glass boxes projecting over a sheer drop of more than 100 storeys."
  },
  {
    title: "Art Institute of Chicago",
    city: "Chicago, IL",
    link: "https://www.artic.edu/",
    image: "https://cdn.thecrazytourist.com/wp-content/uploads/2018/07/ccimage-shutterstock_221446024.jpg",
    ages: 1,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Located in downtown Chicago, the Art Institute is one of the world’s great art museums, housing a collection that spans centuries and the globe."
  },
  {
    title: "Disco NightLife",
    city: "Chicago, IL",
    link: "https://www.discochicago.com/",
    image: "https://theculturetrip.com/wp-content/uploads/2017/06/mid-4.jpg",
    ages: 2,
    duration: 0,
    location: 0,
    activityLevel: 1,
    price: 2,
    approved: false,
    description: "Located above Celeste in River North, Disco wears its retro aspirations on its sleeve, boasting a gigantic lighted dance floor and plenty of massive mirror balls. The playlists are also a conscious throwback to the ’70s, filled with key disco (duh), funk, soul and house music cuts. Show up on Friday and Saturday nights for champagne and dancing in this Instagram-worthy club."
  },
  {
    title: "The Second City",
    city: "Chicago, IL",
    link: "https://www.secondcity.com/",
    image: "https://us-east.manta.joyent.com/condenast/public/cnt-services/production/2015/06/26/558d7bb03f478ebd25626c2e_chicago-second-city-cr-courtesy.jpg",
    ages: 2,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "What is it? Where Bill Murray, Tina Fey, Gilda Radner, Chris Farley and Steve Carell cut their comedic teeth.  Why go? Before they joined the cast of Saturday Night Live or became big-screen stars, those folks above practiced their craft on the mainstage at the Second City. The venue's premiere revue features some of the institutions most talented performers in a series of loosely-connected, topical comedy sketches. "
  },
  {
    title: "Millennium Park",
    city: "Chicago, IL",
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park.html",
    image: "https://cdn.thecrazytourist.com/wp-content/uploads/2018/07/ccimage-shutterstock_468508055.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Discover a state-of-the-art collection of architecture, landscape design and art that provide the backdrop for hundreds of free cultural programs including concerts, exhibitions, tours, and family activities. In Millennium Park, you’ll find a new kind of town square – a lively, spectacular gathering spot located in the heart of the city and a destination for Chicagoans and visitors alike."
  },
  {
    title: "Navy Pier",
    city: "Chicago, IL",
    link: "https://navypier.org/",
    image: "http://s3.amazonaws.com/architecture-org/files/buildings/navy-pier-marco-verch-cc.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Set where the Chicago Portage enters Lake Michigan, the Navy Pier is a multifaceted visitor attraction extending over the water for six city blocks. As one of the top days out in the Midwest, an attraction of this magnitude is hard to sum up in one paragraph. But in 50 acres you’ll come across the vast multisensory Funhouse Maze and the 65-metre Centennial Wheel, footed by fairground rides and amusements. There’s also weekly fireworks in summer, an IMAX Theatre, the Chicago Children’s Museum and the Crystal Gardens botanical garden with more than 80 palms."
  },
  {
    title: "John Hancock Center",
    city: "Chicago, IL",
    link: "https://www.britannica.com/topic/John-Hancock-Center",
    image: "https://cdn.vox-cdn.com/thumbor/ePQF-DEN3xHK3GuYdvT00w8JuKE=/0x0:2006x1336/1200x800/filters:focal(843x508:1163x828)/cdn.vox-cdn.com/uploads/chorus_image/image/60360705/JHC.0.png",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "A mainstay of Chicago’s silhouette, 875 North Michigan Avenue (formerly the John Hancock Center) is a 344-metre skyscraper on the Magnificent Mile. Tapering as it rises, the tower was topped off in 1969 and appears in pretty much any movie that needs an establishing shot for Chicago. Up close you can watch its characteristic X-shaped bracing zigzag up the facades. The view from 360 Chicago on the 94th floor has been rated as one of the best in the country, and the ride up there takes less than 40 seconds. There’s a cafe and bar up, as well as interactive displays labelling the landmarks on the horizon in each direction. If you have a steely disposition try “Tilt”, a glass capsule that tilts forward at 15°, 25° and 40° for a bird’s eye view of the city streets 300 metres below."
  },
  {
    title: "Chicago Cultural Center",
    city: "Chicago, IL",
    link: "https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_culturalcenter.html",
    image: "https://cdn.thecrazytourist.com/wp-content/uploads/2018/07/ccimage-shutterstock_48609508.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Formerly the home of the Chicago Public Library, in 1991 this striking Neoclassical building in The Loop became the first free municipal cultural centre in the United States. There are more than 1,000 exhibitions and programmes here every year and they’re as diverse as you’d expect from a city like Chicago. All for free, you can catch theatre, dance, music, lectures, film screenings and family-oriented events."
  },
  {
    title: "Wrigley Field",
    city: "Chicago, IL",
    link: "https://www.mlb.com/cubs/ballpark/tours",
    image: "https://cdn.thecrazytourist.com/wp-content/uploads/2018/07/ccimage-shutterstock_529214494.jpg",
    ages: 0,
    duration: 0,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "When it comes to Chicago landmarks, perhaps none is so loved as Wrigley Field. Step inside this historic stadium on a Wrigley Field Tour and learn what makes this ballpark unique from guides who bleed Cubbie blue.On these 75- to 90-minute tours, you will have the opportunity to sit in the fan-favorite bleachers, view the field from the press box, enter the clubhouses where your favorite players have been, and even step out onto the hallowed field. Whether you’re a fan of the Chicago Cubs, baseball in general, or just Chicago history, the 90 minutes you'll spend on a Wrigley Field tour is time well spent. Here’s a few highlights from my recent game-day tour."
  },
  {
    title: "Museum of Science and Industry",
    city: "Chicago, IL",
    link: "https://www.msichicago.org/",
    image: "https://cdn.thecrazytourist.com/wp-content/uploads/2018/07/ccimage-shutterstock_62337820.jpg",
    ages: 0,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Limitless inspiration for kids, the Museum of Science and Industry has show-stopping exhibits on an amazing scale. The venue is the old Palace of Fine Arts, built in 1933 in Jackson Park for the World’s Columbian Exposition. Some of the jaw-dropping sights here are a full-size German U-505 submarine captured during the Second World War, the Pioneer Zephyr, a glorious stainless steel diesel locomotive from 1934 and the first Boeing 727 to enter commercial service. Young scientists can wrap their heads around big concepts at the Science Storms exhibit, which has a Tesla coil, Foucault pendulum and Wimshurst machine. There are relics from the Apollo missions at the Henry Crown Space Centre, while the central pavilion has a replica of a deep-shaft bituminous coal mine, in which you’ll take a mine train and see historic equipment from the 1930s."
  },
  {
    title: "Forest Preserves Hikes",
    city: "Chicago, IL",
    link: "https://fpdcc.com/places/trails/?gclid=Cj0KCQjwy97qBRDoARIsAITONTLGXpQG5gi8roDCq-GxQxqN53IP9urY9u81NexSyP9w4QfXbzd__z4aAotCEALw_wcB",
    image: "https://fpdcc.com/wp-content/uploads/2018/09/bike-sunset-aug12-1050x600.jpg",
    ages: 1,
    duration: 0,
    location: 2,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "Explore 70,000 acres of wild & wonderful in the Forest Preserves of Cook County"
  },
  {
    title: "Mob and Crime bus tour",
    city: "Chicago, IL",
    link: "https://chicagocrimetours.com/",
    image: "https://cdn.getyourguide.com/img/tour_img-1743427-145.jpg",
    ages: 2,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "Now their misdeeds are in the distant past, there’s no denying the fascination evoked by Chicago’s prohibition-era mobsters. Names like Al Capone, Bugs Moran and Dion Johnny Torrio remain household names. The city has changed so much in the last century that you’d never guess that benign looking neighbourhoods witnessed a bitter war that claimed scores of lives in the 1920s and 30s. So you have to turn to local historians, and GetYourGuide.com offers a 90-minute Mob and Crime Bus Tour."
  },
  {
    title: "Chicago Symphony Orchestra",
    city: "Chicago, IL",
    link: "https://cso.org",
    image: "https://s3-prod.chicagobusiness.com/CSO%20lede.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 2,
    approved: true,
    description: "As one of America’s “Big Five”, the Chicago Symphony Orchestra is among the most prestigious classical ensembles on the planet. You can see them at the Symphony Center, a National Historic Landmark on South Michigan Avenue. This venue is a complex made up of the Grainger Ballroom, Buntrock Hall and the 2,522-seater Orchestra Hall. On the frieze above the facade’s arches windows you’ll read the names “Bach, Mozart, Beethoven, Schubert and Wagner”. By 2018 Riccardo Muti had been the conductor for eight years."
  },
  {
    title: "Chicago History Museum",
    city: "Chicago, IL",
    link: "https://www.chicagohistory.org/",
    image: "https://static.reservedirect.com/media/product/gallery/original/Chicago_History_Museum_(56334).jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: ""
  },
  {
    title: "Raidio City Music Hall",
    city: "New York, NY",
    link: "https://www.msg.com/venue-tours/radio-city-music-hall?cmp=van_tour",
    image: "https://img.msg.com/wp-content/uploads/2017/08/TonyBennett_091516_204W-L-1590x890-OPT.jpg",
    ages: 1,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "It's where Ella Fitzgerald pined for the man she loved, the Rolling Stones couldn't get no satisfaction and Lady Gaga had a (Bad Romance.) Among performers, there's no New York concert venue that's quite like Radio City Music Hall. You can visit the space for a performance or to get a dose of its lengthy, melodious history on a one-hour Stage Door Tour"
  },
  {
    title: "Coney Island",
    city: "New York, NY ",
    link: "http://coneyislandfunguide.com/",
    image: "https://www.tripsavvy.com/thmb/ZaEC5p_aJpJ7OiUrk-SElURly34=/400x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAM_9187-5c7ed3f846e0fb0001edc925.jpg",
    ages: 0,
    duration: 2,
    location: 2,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "From roller-coasters to go-karts, to live entertainment and boardwalk games, beachfront Coney Island has it all! The world famous Coney Island is a year-round destination full of fun things to do, both historic and new.  The birthplace of the amusement park, Coney Island is home to an Aquarium, Action-Packed Rides, Restaurants, Shops and Sideshows, Coney Island has something for everyone."
  },
  {
    title: "Brooklyn Botanic Garden",
    city: "New York, NY ",
    link: "https://www.bbg.org/",
    image: "https://www.bbg.org/img/uploads/manual/hero/_list_thumbnail_retina/woman-summer-flowers_BB_43134032811.jpg",
    ages: 0,
    duration: 1,
    location: 2,
    activityLevel: 0,
    price: 0,
    approved: false,
    description: "Wander along Brooklyn's Washington Avenue, and you can't avoid stumbling upon this verdant 52-acre park. A main highlight here is the Japanese Hill-and-Pond Garden, punctuated by wooden bridges and Japanese maples. And if you arrive at the end of April, you can't miss the Cherry Esplanade (Sakura Matsuri) when rosy cherry blossoms burst into bloom."
  },
  {
    title: "Chrysler Building Skyscraper Center",
    city: "New York, NY ",
    link: "http://www.skyscrapercenter.com/building/chrysler-building/422",
    image: "https://cdn.cnn.com/cnnnext/dam/assets/190109075400-01-chrysler-building-file-exlarge-169.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 1,
    price: 0,
    approved: true,
    description: "The Chrysler Building was the first supertall building taking the title of World's Tallest Building after winning a height battle with The Bank of Manhattan. The building claimed the title when it raised an 125-foot spire in just 90 minutes after constructing it in secret. It lost the title of World's Tallest Building 11 months later to the Empire State Building but enjoyed commercial success due to its location next to Grand Central Terminal. In 2009, the Chrysler Building went through a retrofit, gaining the certification LEED Gold for Existing Buildings."
  },
  {
    title: "Empire State Building",
    city: "New York, NY ",
    link: "https://www.esbnyc.com/",
    image: "https://www.esbnyc.com/sites/default/files/health_food_balance-p_bis465nnxmf.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "You really can't miss seeing the Empire State (it's the second-tallest building in New York City only to the recently topped-out One World Trade Center), but in case you do, look toward midtown Manhattan at the intersection of Fifth Avenue and West 34th Street (take the B, D, F, M, N, Q, or R train to 34th Street). The 86th- and 102nd-floor observatories are open every day from 8 a.m. until 2 a.m.; the last elevator is at 1:15 a.m. Tickets to the 86th floor cost $36 for adults, $35 for seniors and $31 for children, or $69 for the Express Pass (where you can bypass the line). "
  },
  {
    title: "Grand Central Terminal",
    city: "New York, NY ",
    link: "https://www.grandcentralterminal.com/",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Grand_Central_Terminal_celing_view.jpg/220px-Grand_Central_Terminal_celing_view.jpg",
    ages: 0,
    duration: 0,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "Be transported by the iconic beauty and lasting legacy of Grand Central Terminal. This historic world-famous landmark in Midtown Manhattan is not simply a transportation hub—it’s also a shopping, dining, and cultural destination with 60 shops, 35 places to eat, and a full calendar of events all under one magnificent roof. Opened to the public in February 1913, Grand Central Terminal is a story of great engineering, survival, and rebirth. In 1978, architect Philip Johnson and First Lady Jacqueline Kennedy Onassis campaigned to secure landmark status for the Terminal, ensuring the building would serve New Yorkers for generations to come. "
  },
  {
    title: "Metropolitan Museum of Art",
    city: "New York, NY ",
    link: "https://www.metmuseum.org/",
    image: "https://www.metmuseum.org/-/media/images/homepage/locations/fifth-avenue/fifth_ave_mobile_darkened2_final.jpg",
    ages: 1,
    duration: 1,
    location: 0,
    activityLevel: 0,
    price: 0,
    approved: true,
    description: "No museum in the United States is as celebrated as the Metropolitan Museum of Art. Spilling over with masterpieces from all over the world, including notable collections from Ancient Egypt and classical antiquity, the Met is an art experience unlike any other, and like much in New York, it's impossible to see all the museum has to offer in one day (or even two days, for that matter)."
  },
  {
    title: "BronxZoo",
    city: "New York, NY ",
    link: "https://bronxzoo.com/",
    image: "https://c532f75abb9c1c021b8c-e46e473f8aadb72cf2a8ea564b4e6a76.ssl.cf5.rackcdn.com/2019/04/22/3vhg5w62c0_zoo_center.jpg",
    ages: 0,
    duration: 1,
    location: 1,
    activityLevel: 0,
    price: 1,
    approved: true,
    description: "According to travelers, these 265 acres sheltering more than 4,000 animals should be near the top of every young family's itinerary in New York. And if you're an older visitor, the Bronx Zoo could be a great way to escape the nonstop activity in Manhattan. If you're not an animal lover, however, stay far away – this zoo's claim to fame is that it's the largest metropolitan animal park in the country."
  },
]

db.AddEvent
  .remove({})
  .then(() => db.AddEvent.collection.insertMany(eventSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
